import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'DBMS',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Oracle',
          link: {type: 'generated-index', description: 'Oracle Database Deep Dive & Optimization'},
          items: [{type: 'autogenerated', dirName: 'dbms/oracle'}],
        },
        {
          type: 'category',
          label: 'PostgreSQL',
          link: {type: 'generated-index', description: 'PostgreSQL Architecture & Core Internals'},
          items: [{type: 'autogenerated', dirName: 'dbms/postgres'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'CASE',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: '2026 1Q',
          link: {type: 'generated-index', description: '2026년 1분기 장애 분석 및 개선 리포트'},
          items: [{type: 'autogenerated', dirName: 'case/2026-1Q'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'AI Agent',
      collapsible: true,
      collapsed: false,
      link: {type: 'generated-index', description: 'LLM & Autonomous DBA Agent 아키텍처'},
      items: [{type: 'autogenerated', dirName: 'agent'}],
    },
  ],
};

export default sidebars;